### ISSUE TITLE
[1.5][ahdigital][2] No warning when use private browsing

### ISSUE THREAD

**Issue by AboShanab** [bitshares/bitshares-ui#1190]
Hello there, how are you today?
After the latest update of bitshares-ui (2.0.180215), when I use the private browsing in Firefox 58.0.2 there's no warning message appear for me inform me about Can't access local storage while using private browsing just like past versions, Here's the screen shots between the latest version and the past version:

Past version (OpenLedger exchange):
<img width="290" alt="screenshot_1" src="https://user-images.githubusercontent.com/12101368/36342348-434b6af0-140e-11e8-8f88-441dd8546dbc.png">

New version (Bitshares exchange):
<img width="948" alt="screenshot_2" src="https://user-images.githubusercontent.com/12101368/36342354-71456c26-140e-11e8-82eb-a9ff6b3e22a0.png">
Still the process like that, and never changed.

Here's a screenshots of the console log:
https://imgur.com/a/H6Epd

Thanks for your efforts.
Regards,
AboShanab

**Comment by pnomolos** [comment]
@AboShanab Did you upgrade to Firefox 57/58 recently?  It appears that this may be due to a long-standing bugfix in FireFox (where localStorage is now cleared when private mode is exited - see https://bugzilla.mozilla.org/show_bug.cgi?id=1047098) as opposed to a change in the BitShares ui.

**Comment by AboShanab** [comment]
@pnomolos, Yes, I use 58.0.2 (64 bit) as I said here before. The cache and history is already cleared and the problem is still appear.

**Comment by pnomolos** [comment]
Hi @AboShanab I understand that you’re on 58 now, did the warning previously appear when using version 58?  I know that how localStorage is handled changed recently in Firefox, which is why I’m trying to rule out as much as I can :)

**Comment by AboShanab** [comment]
@pnomolos, In the new version of BitShares in Firefox 58 never appear any warning previously
In the past version of BitShares like 2.0.180115 the warning is appear in Firefox 58.

**Comment by pnomolos** [comment]
Thank you! That’s what I wanted to confirm. Unfortunately I’m not sure what
may be the cause but I’ll see if I can replicate.

**Comment by wmbutler** [comment]
Display warning when using private browsing on all platforms, specifically when creating the local wallet. The local wallet stores important information in a local database and it would be very easy for a user to create a local wallet and lose access to it if they are in incognito mode.

@ahdigital this needs UX. It basically needs a warning in between **advanced form** and the local wallet creation screen warning the user that if they fail to backup their wallet, the account will be lost and inaccessible.

**Comment by AboShanab** [comment]
I see other bugs in private browsing, when clicking voting in the dropdown menu. it's load with account called "null" and without any response also Explore tap doesn't appear data of the exchange at all, and still pending like the past photo. (I just want to say most of the features are corrupted in the private mode).
<img width="956" alt="screenshot_1" src="https://user-images.githubusercontent.com/12101368/36892947-6fb14de0-1e17-11e8-8a3f-004a4483169a.png">

**Comment by calvinfroedge** [comment]
We had previously decided to disable incognito mode altogether (in fact I wrote that code) and that got overturned somehow. Really need clear input / direction on how to proceed here. Should we just be putting warnings in certain places? @wmbutler I can put in some simple UX if you just want me to proceed on this part:

`needs a warning in between advanced form and the local wallet creation screen warning the user that if they fail to backup their wallet, the account will be lost and inaccessible.`

**Comment by calvinfroedge** [comment]
@wmbutler If you can tell me whether we should disable incognito altogether or only show dismissable warnings at certain points (please tell me where) I can just knock this out.

**Comment by wmbutler** [comment]
It's a bad idea to disable incognito, especially for the cloud wallet where it's perfectly acceptable. In the case of the local wallet (key file), it's really dangerous because a use who creates a local wallet account under incognito and then fails to download that key file will permanently lose access to their account.

**Comment by ahdigital** [comment]
For local wallet (key file) users we should show a prominent, dismissable warning. Rather than a modal / alert box style warning though, something like this would highlight the dangers better.

![image](https://user-images.githubusercontent.com/3088454/37959780-cf8a67a4-31ab-11e8-866f-2c6eb4a5e7e4.png)

This warning could persist on every page until dismissed, or display only on account creation. I'd lean towards the former though.

Since incognito for cloud wallets (account name & password) is acceptable we need to provide fall backs for cases where a page relies on an account being set, or fixes where a page won't load.

I've just tested browsing in incognito and I couldn't find a page which wouldn't render though.

**Comment by wmbutler** [comment]
I like this, but let's be more direct:

"If you close your browser without backing up, you will lose this account permanently."

**Comment by ahdigital** [comment]
Thanks. I used your wording and retained the 'Private/incognito' and 'Backup now' text to give the user reason and action.

The bar is 34px in height, and the text is 14px (0.875rem). Bar colors for each theme are:

**Midnight**: #e3745b
**Dark:** #ff3950
**Light:** #ea340b

The dismiss SVG icon is attached in [dismiss.zip](https://github.com/bitshares/bitshares-ui/files/1855139/dismiss.zip)


![image](https://user-images.githubusercontent.com/3088454/38017901-54de9140-326b-11e8-9386-f24e91fc9706.png)

**Comment by calvinfroedge** [comment]
Resolved by https://github.com/bitshares/bitshares-ui/pull/1366

**Comment by AboShanab** [comment]
@calvinfroedge your solution doesn't work well, the problem is still with other errors.
<img width="959" alt="screenshot_13" src="https://user-images.githubusercontent.com/12101368/38176420-0f050ae8-35f7-11e8-9272-88fc975ad5e5.png">
also still there's no error appear for me, here's the debugging and console screenshots:
<img width="960" alt="screenshot_14" src="https://user-images.githubusercontent.com/12101368/38176426-559ff4f4-35f7-11e8-8cae-63a403825631.png">
<img width="960" alt="screenshot_15" src="https://user-images.githubusercontent.com/12101368/38176427-55cba81a-35f7-11e8-941e-9e8467d00e50.png">
 also high memory usage on Firefox 59.0.2 (I think the problem is the process is still waiting without any response from the server)
<img width="461" alt="screenshot_16" src="https://user-images.githubusercontent.com/12101368/38176439-907ec578-35f7-11e8-8cfc-abe2c66afe99.png">
The memory usage is about 3,684,4 MB.

Thanks for your efforts guys but please be patient before release an new update.

**Comment by AboShanab** [comment]
Please Leave the ticket open while the problem is doesn't fixed...

**Comment by wmbutler** [comment]
This issue was resolved properly. Keeping it closed.

<img width="1520" alt="screen shot 2018-04-01 at 2 14 12 pm" src="https://user-images.githubusercontent.com/1254810/38176574-06768ffe-35b7-11e8-976d-f0a7ac8deb91.png">

**Comment by AboShanab** [comment]
@wmbutler As you see on Firefox, I join the same page of register on private mode and the notification still doesn't appear
<img width="960" alt="screenshot_17" src="https://user-images.githubusercontent.com/12101368/38176602-9cc65de8-35fa-11e8-8fb0-a95c1c36e8ce.png">
Maybe the problem is on Firefox only?

**Comment by wmbutler** [comment]
@AboShanab That's the cloud wallet. No need for the warning because no localstorage is used. There is no concern with loss.

**Comment by AboShanab** [comment]
@wmbutler but still I can't do anything while I'm using the private mode on Firefox, even on the cloud wallet, the statics of the exchange doesn't appear also anything other.

**Comment by wmbutler** [comment]
Still has nothing to do with this issue.
