### ISSUE TITLE
[.5] White Screen

### ISSUE THREAD

**Issue by mazaw19** [bitshares/bitshares-ui#1810]
**Describe the bug**
Build 2.0.180815: I just updated to the latest build, and nothing loads. I just get a white screen. I try to reload the page, but nothing
<img width="1920" alt="bitshares bug" src="https://user-images.githubusercontent.com/42746281/44940225-cf2ec700-ad48-11e8-98e3-2bc886b3d05b.png">
. 

**To Reproduce**
I just updated to the latest Ui. I did nothing else. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - Version: 2.0.180815
**
Smartphone (please complete the following information):**

**Additional context**

**Comment by mazaw19** [comment]
Note: 2.0.180808-rc2 is the latest build working for me.

**Comment by startailcoon** [comment]
Can you please post some of the logging output you have when you open "View" -> "Toggle DevTools" and check the tab "Console".

**Comment by mazaw19** [comment]
<img width="1331" alt="bitshare bug" src="https://user-images.githubusercontent.com/42746281/44949048-c987be80-ade6-11e8-9dfc-fc9452d5ad3e.png">

**Comment by startailcoon** [comment]
It seems like there is an issue with a field not being correct when you start your client. Something is missing the `url` field.

You can try to remove a few settings stored in the app to get you started again. As this shouldn't be happening, and it used to work for you before, I suspect there is a field somewhere in the settings that doesn't comply with the app anymore.

**Note that you should NOT remove all your settings, PLEASE follow these directions**

- Open `Toggle Dev Toos`
- Click the tab `Application`
- Under Storage, expand `Local Storage`.

Try with removing the follow, and ONLY the following keys by selecting it and clicking the ´DEL´ key.
- `__graphene__defaults_v1`
- `__graphene__settings_v3`
- `__graphene__settings_v4`

Restart or Reload the app to see if you still have the same issue.

**Comment by mazaw19** [comment]
Hey that did it!

**Comment by sschiessl-bcp** [comment]
nodes[currentNodeIndex] is null if a node got removed from defaults that did exist before.

https://github.com/bitshares/bitshares-ui/blob/f40e94928a04e3bde9e24be2ee57724404ca29e3/app/components/Layout/Footer.jsx#L316

Fixed like that
![image](https://user-images.githubusercontent.com/33128181/44979803-5b6e0380-af6e-11e8-8185-2e7ac02ba158.png)

I had that done locally but didnt push it yet..

**Comment by RobJah** [comment]
Well i still have the issue on my laptop with all my wallets. I tried startailcoin's fix. Didnt change anything about the issue on my end. 

Please assist as i am starting to panic lol

**Comment by sschiessl-bcp** [comment]
What version are you running?

**Comment by RobJah** [comment]
I now also re-did all the steps there were, cleaning browser, toggle on the automatic time and date windows thing and toggle it off again. reloaded, and it works again. 

thnx a bunch ppl!

**Comment by RobJah** [comment]
Sorry guys to reopen this one, but i got a white screen on my local wallet again. downloaded the latest release when it came out last week, and used it without a problem untill today.

![image](https://user-images.githubusercontent.com/43188591/56598485-dd419880-65f4-11e9-8cb0-6b3fc1529f35.png)

checked the system clock 10 times already, toggled the shit out of it, so now the FUD is starting to creep into my brain. What steps can i take to resolve the problem or what info am i missing that you guys need to help me?

thanks!

**Comment by RobJah** [comment]
after changing nothing but reloading at least 50 times, the wallet responds again.
thanks :p

**Comment by bmess12** [comment]
I am running latest version. Under "local storage" the first fix option above lists different "graphene" options. I have tried- EVERYTHING many times over. Nothing is working. Both web and download version non pc or tablet. Please help

**Comment by sschiessl-bcp** [comment]
Can you check what your browser console log says when whitescreen on pc please?

**Comment by atmguru** [comment]
I have the same exact white screen. I'm using ver 2.0 18015 and I use a Mac Catalina 10.15.6 and have tried reloading and it's still blank.  Help!  TYVM

**Comment by abitmore** [comment]
@atmguru please download the latest version from https://github.com/bitshares/bitshares-ui/releases .

**Comment by bmess12** [comment]
turn your pc clock 1 hour ahead.  if that doesnt work turn back 1 hour from actual time.  also soemtiems vpn can interfere, make sure you dl latest version

**Comment by atmguru** [comment]
@abitmore thank you that worked!!
