### ISSUE TITLE
Increment for BUY/SELL ORDER click

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2700]
**Is your feature request related to a problem? Please describe.**
When filling the order book, I want to place my order slightly ahead of certain spots. 
Now it depends on the rounding error, where my new order will be placed or I have to manually edit my sell/buy price.  

**Describe the solution you'd like**
The BUY ORDER click should be multiplied  by (1 + 10⁻5) for the input field number.
The SELL ORDER click should be multiplied  by (1 - 10⁻5) for the input field number.

**Additional context**
This should also help to improve order book depth and spread.

**Comment by startailcoon** [comment]
When you click on the orderbook row of another order, that is the price your form will fill out. You have to manually change that price to suit your needs. I don't think we should manipulate the price to anything else as the user would expect the price to be that one and nothing else.

However, I see your point, but can't see that we have any good ways to handle them automatically for the user without making it all very confusing.

**Comment by froooze** [comment]
My idea was to highlight a `border-top/bottom`, when mouse is on the edge, to another row.

1. Click on the center, nothing change.
2. Click on the edge with a border highlight, new behavior

**Comment by sschiessl-bcp** [comment]
I find the idea quite interesting. 

![image](https://user-images.githubusercontent.com/33128181/58423382-405f9880-8095-11e9-9049-1d14e32a60b1.png)

If you hover to the boarder, you see a label slide in, something like this
![image](https://user-images.githubusercontent.com/33128181/58423482-874d8e00-8095-11e9-9b62-b658e23de3da.png)
Clicking on label puts your order with an %-offset that can be defined in Personalize

**Comment by startailcoon** [comment]
I like the possibility of your idea @sschiessl-bcp. Making this possible when you hover with a mouse I see no issues with. A mobile device is a but trickier. But if we can find a good way to do this, perhaps it can help with https://github.com/bitshares/bitshares-ui/issues/2563

**Comment by abitmore** [comment]
I thought I've fixed the rounding error, when you click on the order book you always get a price which is able to fill when you click. However, because some markets are moving quickly, when confirming the new order, perhaps it won't fill, that's why people want to manually adjust price after clicked. 

A simple approach for the user is to click on an order deeper on the book but not the top ones. Or we can a button to slightly decrease selling price.

For people who don't want their orders to be matched instantly, a button to slightly increase selling price makes sense.

So my idea is to add two buttons in the "new order" box, price row, E.G.
```
Price [-] [+]      123.456  BTS/bitUSD
```
![image](https://user-images.githubusercontent.com/9946777/58439084-bfbf8d00-80d2-11e9-91e2-7998d9924490.png)

**Comment by froooze** [comment]
> I thought I've fixed the rounding error, when you click on the order book you always get a price which is able to fill when you click. However, because some markets are moving quickly, when confirming the new order, perhaps it won't fill, that's why people want to manually adjust price after clicked.

Sometimes I am ahead of the clicked order, sometimes I am behind the clicked order

> A simple approach for the user is to click on an order deeper on the book but not the top ones. Or we can a button to slightly decrease selling price.

Doesn't solve the problem.

> For people who don't want their orders to be matched instantly, a button to slightly increase selling price makes sense.

If I increase my buy order or decrese my sell order, my order will be matched more likely. 

> So my idea is to add two buttons in the "new order" box, price row, E.G.
Or rethink the rounding ?

> When clicking on `[-]`, decrease price by 0.1%. When clicking on `[+]`, increase price by `0.1%`.
Please keep in mind (1+10⁻5)^100 is a increase of 0.1%

Options:
- Auto increase/decrease by 10^(-5) without any UI extras
- Increase/decrease by custom amount with UI overlay in orderbook
- Increase/Decrease buttons by custom amount on input form 
- Rethink rounding to only one direction

I favorite the last two options

**Comment by abitmore** [comment]
Current behavior is: if you click on a sell order on the order book, don't change the price, submit a buy order, then your order **will match** with the sell order. If your order didn't match, then it's a bug related to rounding, which should have been fixed in https://github.com/bitshares/bitshares-ui/pull/565.

@froooze I guess I got what you want. You clicked on a sell order on the order book, and submitted a new sell order, you expected that your sell order will be in front of the order you clicked. Yes, this is a new feature. The UI don't know whether the user want to place a new order in front of the order she clicked, thus buttons to quickly adjust price makes sense.

**Comment by abitmore** [comment]
About UX:

When placing a new order, `price * amount1 = amount2`.

On many exchanges, traders input price and amount1, the amount2 is derived.

On BitShares, actually traders input 2 amounts, the price is derived.

So, for the feature requested in this issue, it's wise to lock the smaller (in Satoshi) amount and adjust the bigger amount by 1 Satoshi or a few Satoshis, let the price change by itself. It's annoying that there is no lock button on trading page like we have when adjusting debt position.

**Comment by startailcoon** [comment]
Regarding locking any of the inputs, like we have on the debt position we have issue #2075 on that. I guess that issue would solve this one, perhaps together with an easy way to increase/decrease the non-locked input field.
