### ISSUE TITLE
infinite loops - missing path 'assets/BTS' for locale 'ru' #2789

### ISSUE THREAD

**Issue by gades** [bitshares/bitshares-ui#2938]
The issue still not fixed. please reopen ticket

<img width="1112" alt="Screen Shot 2019-07-12 at 23 07 25" src="https://user-images.githubusercontent.com/4200730/61155757-523cb400-a4fa-11e9-9110-30dccbcad193.png">

**Comment by gades** [comment]
For replicate this issue please:

generate bundle npm run package-mac
run app and go to dashboard->portfolio->bts

**Comment by gades** [comment]
<img width="404" alt="Screen Shot 2019-07-13 at 10 54 17" src="https://user-images.githubusercontent.com/4200730/61168829-9791cd80-a55c-11e9-9fea-58a1c5619640.png">


`app.fa1c5856d7d37943d92e.js:1 Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at e.exports (https://wallet.piratecash.net/vendor.4b12c3ad4b2205507ab8.js:148:92239)
    at p (https://wallet.piratecash.net/vendor.4b12c3ad4b2205507ab8.js:148:258)
    at ga (https://wallet.piratecash.net/vendor.4b12c3ad4b2205507ab8.js:148:78983)
    at Object.enqueueSetState (https://wallet.piratecash.net/vendor.4b12c3ad4b2205507ab8.js:148:54504)
    at t.b.setState (https://wallet.piratecash.net/vendor.4b12c3ad4b2205507ab8.js:140:1283)
    at t.value (https://wallet.piratecash.net/app.e9cead80970fbbcfe2ad.js:1:628278)
    at n (https://wallet.piratecash.net/app.e9cead80970fbbcfe2ad.js:1:628600)
    at console.error (https://wallet.piratecash.net/app.e9cead80970fbbcfe2ad.js:1:629059)
    at Fi (https://wallet.piratecash.net/vendor.4b12c3ad4b2205507ab8.js:148:72013)
    at t.Wi.r.componentDidCatch.n.callback (https://wallet.piratecash.net/vendor.4b12c3ad4b2205507ab8.js:148:75051)`

**Comment by startailcoon** [comment]
You're using some other wallet on `wallet.piratecash.net`. I assume they haven't deployed the develop branch yet, as this has not on the main released yet. 

It should be fixed on develop.bitshares.org.

**Comment by startailcoon** [comment]
You're using some other wallet on `wallet.piratecash.net`. I assume they haven't deployed the develop branch yet, as this has not on the main released yet. 

It should be fixed on develop.bitshares.org.

**Comment by OpenLedgerApp** [comment]
@startailcoon let me check it

**Comment by gades** [comment]
@OpenLedgerApp it still doesn't work !!! PLEASE DOUBLE CHECK IT

<img width="1664" alt="Screen Shot 2019-07-22 at 13 52 35" src="https://user-images.githubusercontent.com/4200730/61627299-13d88f00-ac88-11e9-9e2e-b11cde9527cb.png">

**Comment by startailcoon** [comment]
@gades please let the developers try to look at it. You've reported the issue and the developers will look at fixing it.

**Comment by gades** [comment]
@startailcoon this issue can be reproduced only after build application, in case run this one from `npm start` is working fine. i'm thinking this is related to build application

**Comment by startailcoon** [comment]
@OpenLedgerApp will have an easier time finding it with that information. Sounds about right, based on the persistence of this.
