### ISSUE TITLE
[2] Bug in new Account Creation

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#521]
bitshares.eu migrated the new sign-up, and while I was able to create an account yesterday, tests today show errors.

![](https://i.imgur.com/y7DU3cI.png)

this needs attention prior to the release @wmbutler 

@xeroc

**Comment by btsfav** [comment]
Console:

app.js:23 referralAccount e15712aee74b4732-60677f2a122c483c
app.js:43 WebSocket connection to 'wss://bit.btsabc.org/ws' failed: Error during WebSocket handshake: Unexpected response code: 404
open @ app.js:43
/?r=e15712aee74b4732-60677f2a122c483c:1 WebSocket connection to 'wss://bts.transwiser.com/ws' failed: WebSocket is closed before the connection is established.
/?r=e15712aee74b4732-60677f2a122c483c:1 WebSocket connection to 'wss://secure.freedomledger.com/ws' failed: WebSocket is closed before the connection is established.
/?r=e15712aee74b4732-60677f2a122c483c:1 WebSocket connection to 'wss://altcap.io/ws' failed: WebSocket is closed before the connection is established.
/?r=e15712aee74b4732-60677f2a122c483c:1 WebSocket connection to 'wss://bitshares.dacplay.org/ws' failed: WebSocket is closed before the connection is established.
app.js:43 Connected to API node: wss://bitshares.openledger.info/ws
app.js:7 synced and subscribed, chainstore ready
app.js:43 INFO	browserEntropy gathered
app.js:29 create account: jjksh2
app.js:29 new active pubkey BTS5WBtdo34WrHHDaRHsjNNrYgXj9LmJBfs9PnReMDEvgJWorUaDg
app.js:29 new owner pubkey BTS53NDVE2vK2WaNr4LLNg7TKmeyLGdAc6u5ERywaE5SvfrweMdDd
18.js:1 ERROR AccountActions.createAccount Objectbase: ["Assert Exception: current_account_itr == acnt_indx.indices().get<by_name>().end():"]__proto__: Object

**Comment by wmbutler** [comment]
Will you please post a licecap screencast? I cannot duplicate this.

**Comment by btsfav** [comment]
just talked with a new user on telegram, same issue with bitshares.eu - definitely not alone with this one.

https://www.useloom.com/share/9de35cdb8c664c67a0cac8f91281c054

**Comment by wmbutler** [comment]
It doesn't look like that code was ready for production yet. We haven't even implemented it at bitshares.org/wallet yet.

![screen shot 2017-10-08 at 12 15 19 pm](https://user-images.githubusercontent.com/1254810/31319070-8dd0a2e2-ac22-11e7-97a2-a726e263a3a7.png)

**Comment by btsfav** [comment]
forked in with https://github.com/bitshares/bitshares-ui/issues/506 and would be live in the next release.

Fix it now, if this bug is in the next release, someone is not getting paid.

**Comment by wmbutler** [comment]
Needs to be rolled back on their site. This code has not been released yet.

**Comment by svk31** [comment]
I don't know what that bug is, it's not from the front-end but rather from the backend API node. Nothing has been changed with respect to how account creations are done on our end, the changes were purely visual.

@abitmore @pmconrad Any idea what that error means?

**Comment by wmbutler** [comment]
@svk31 I'm happy to test it before it gets rolled out. Which branch is it on currently? Were you planning to release it soon?

**Comment by btsfav** [comment]
@svk31 something must've been changed. I was able to register the account via bitshares.org/wallet

**Comment by svk31** [comment]
It's an issue with the faucet xeroc is using on that site, creating a new account with the standard Openledger faucet works fine. `https://faucet.bitshares.eu`

@xeroc

**Comment by Tommixoft** [comment]
When this will be fixed can not create account. :(

**Comment by wmbutler** [comment]
This should have been closed. I do not believe this bug exists. Post a licecap @Tommixoft

**Comment by Tommixoft** [comment]
@wmbutler i got this error with newest UI wallet and Online wallet 8 times. Then i left ui wallet in create account window...and after 2minutes i've looked and account was created and logged in. Anyway this error still exists.

**Comment by wmbutler** [comment]
Actually, I agree, just tested creating a new account: 

Web: wallet.bitshares.org
Node: Los Angeles, USA
Cloud Wallet

**Comment by wmbutler** [comment]
```
Connected to API node: wss://la.dexnode.net/ws
app.js:2 synced and subscribed, chainstore ready
/#/:1 [DOM] Found 2 elements with non-unique id #username: (More info: https://goo.gl/9p2vKq) 
<input type=​"text" name=​"username" id=​"username" value placeholder=​"Account name" tabindex=​"1" style=​"text-transform:​ lowercase;​ font-variant:​ initial;​">​
 
<input type=​"text" name=​"username" id=​"username" value=​"eoerpotiero-eretertretretrrt" placeholder=​"Account name" tabindex=​"1" style=​"text-transform:​ lowercase;​ font-variant:​ initial;​">​
3
app.js:52 INFO	browserEntropy gathered
app.js:14 create account: eoerpotiero-eretertretretrrt
app.js:14 new active pubkey BTS8AEs2mzMqeJpzWJPSvRrDDAV9sLGAY9hjhyC5p2FZMQffKZsQm
app.js:14 new owner pubkey BTS7RuYWiCpELJKRU9E294kM2C1NtpdYNNgDFh1kdK18W5byumnyU
app.js:93 ERROR AccountActions.createAccount 
Object
base
:
Array(1)
0
:
"Assert Exception: current_account_itr == acnt_indx.indices().get<by_name>().end():"
length
:
1
__proto__
:
Array(0)
__proto__
:
constructor
:
ƒ Object()
hasOwnProperty
:
ƒ hasOwnProperty()
isPrototypeOf
:
ƒ isPrototypeOf()
propertyIsEnumerable
:
ƒ propertyIsEnumerable()
toLocaleString
:
ƒ toLocaleString()
toString
:
ƒ toString()
valueOf
:
ƒ valueOf()
__defineGetter__
:
ƒ __defineGetter__()
__defineSetter__
:
ƒ __defineSetter__()
__lookupGetter__
:
ƒ __lookupGetter__()
__lookupSetter__
:
ƒ __lookupSetter__()
get __proto__
:
ƒ __proto__()
set __proto__
:
ƒ __proto__()
```

**Comment by wmbutler** [comment]
@xeroc pinging you since this could be related to faucet.

**Comment by btsfav** [comment]
sigh, how hard is it to keep a faucet working? super annoying to monitor and need to change all ref links all the fkn time

**Comment by wmbutler** [comment]
@xeroc can you address this?

**Comment by SebiTimeWaster** [comment]
I have the same bug with the BitShares2-light wallet (which i presume is just a browser opening https://wallet.bitshares.org/ ?) under linux since days now (cannot register at all).

**Comment by Tommixoft** [comment]
yeah i had it too when was trying to register...finally i gave up and left wallet sit open..then after 5minutes i see i'm loged in :)

**Comment by SebiTimeWaster** [comment]
unfortunately didn't work for me so far...

**Comment by wmbutler** [comment]
@svk31 I originally thought this was related to the faucet, but I think it's worth you observing it from the production network rather than the test net.

**Comment by svk31** [comment]
The error message is from the faucet, meaning it's a faucet issue not GUI.

**Comment by wmbutler** [comment]
@xeroc I closed this, but please place some monitoring on the faucet or add some redundancy.

**Comment by btsfav** [comment]
@wmbutler is it working again?

**Comment by wmbutler** [comment]
I haven't tested it, but my understanding is that it was a faucet issue and has nothing to do with the UI.

**Comment by btsfav** [comment]
@xeroc ?

**Comment by xeroc** [comment]
> @xeroc pinging you since this could be related to faucet.

The faucet is API compatible with the previous faucet software. Can you elaborate on the JS issue?

For the record ... the faucet is working all fine and registered many thousand accounts in the first 2 weeks.

**Comment by btsfav** [comment]
@wmbutler @svk31 please re-open and check this ASAP. should've been fixed like 4 days ago...

**Comment by xeroc** [comment]
Turns out .. the error message was produced by the backend. A restart of the faucet fixed the problem. I will investigate the root cause of this issue .. Please ping me if this happens again

**Comment by btsfav** [comment]
@wmbutler account creation works for now, I suggest to take this off of milestone

**Comment by wmbutler** [comment]
Uh, I closed it 2 days ago.

**Comment by mistdale** [comment]
Appears from time to time, in python-bitshares lib (xeroc) v0.1.11, when creating new account. Sometimes it works, sometimes yields this error. Can't figure out exact causes.

**Comment by SeavantUUz** [comment]
reproduced. ether the desktop version or website.

**Comment by wmbutler** [comment]
This is typically a faucet issue. Is it working now @SeavantUUz ?

**Comment by youaresofunny** [comment]
Hello, we also started to receive this error:
``"current_account_itr == acnt_indx.indices().get<by_name>().end():"``

**Comment by abitmore** [comment]
@youaresofunny "current_account_itr == acnt_indx.indices().get<by_name>().end():" means the account name already exists.

**Comment by youaresofunny** [comment]
@abitmore ah, thx

**Comment by xeroc** [comment]
@abitmore that error is raised by the backend after some time even if the account name has not been registered before.

The faucet checks for dublicated accounts first, then tries register. Somebtimes then throws the error at backend. This is fixed by restarting the faucet :/

**Comment by SeavantUUz** [comment]
@wmbutler works fine for me now. Thx.

**Comment by KINGdotNET** [comment]
Today (March 16) the create account still an issue using the https://wallet.bitshares.org
Anyone know where I can create my own account ?

**Comment by abitmore** [comment]
@xeroc restart faucet or the node? Perhaps the client (web browser) sent same request twice e.g. due to a refresh, so the second request will trigger that error?

**Comment by KINGdotNET** [comment]
In my case, I've used two different computers same error message.

**Comment by abitmore** [comment]
@KINGdotNET try register one on https://openledger.io/?

**Comment by KINGdotNET** [comment]
What is the difference between bitshares.org and openledger.io? Will I be able to login using my wallet to any of them or only to openledger.io where I created my account?

**Comment by abitmore** [comment]
@KINGdotNET once created, the same account can be used everywhere. Perhaps you can try again on wallet.bitshares.org, I just successfully created an account. Make sure you don't have something special in the name. If you got an error, please post a screenshot here.

**Comment by KINGdotNET** [comment]
@new-bot like @abitmore suggested, you the other website  https://openledger.io/ to create your account. It works for me.
