### ISSUE TITLE
[.5][HarukaMa] Remove "sign as owner" feature after back end bug got fixed

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#754]
The "sign as owner" feature is designed to get around a bug in back end (https://github.com/bitshares/bitshares-core/issues/496). **After** that bug got fixed, we should remove the "sign as owner" feature to reduce user confusion.

**Comment by abitmore** [comment]
The bug has been fixed in `develop` branch. Will likely be included in next BitShare-Core release.

**Comment by HarukaMa** [comment]
I would against doing this now as many api nodes in the public list currently are not using 2.0.171212 release. That release fixes the spikes on market charts, but I'm still seeing some nodes return chart data with spikes, which means they are not running with the `get_potential_signatures` fix. If we remove that now there may still be problems.

I'd claim this though, but please reconsider if we want it removed now.

**Comment by HarukaMa** [comment]
I'm blocked by bitshares/bitshares-core#567, waiting for the answer.
